# ═══════════════════════════════════════════════════════════════════════════════
#  █████╗ ██╗      █████╗  ██████╗██████╗ ██╗████████╗████████╗██╗   ██╗
# ██╔══██╗██║     ██╔══██╗██╔════╝██╔══██╗██║╚══██╔══╝╚══██╔══╝╚██╗ ██╔╝
# ███████║██║     ███████║██║     ██████╔╝██║   ██║      ██║    ╚████╔╝ 
# ██╔══██║██║     ██╔══██║██║     ██╔══██╗██║   ██║      ██║     ╚██╔╝  
# ██║  ██║███████╗██║  ██║╚██████╗██║  ██║██║   ██║      ██║      ██║   
# ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝   ╚═╝      ╚═╝      ╚═╝   
## ══════════════════════════════════════════════════════════════════════════════
# 🎯 BEAUTIFUL TERMINAL
# ══════════════════════════════════════════════════════════════════════════════
[window]
opacity =  1
padding.x = 2
padding.y = 1

[font]
size = 16.0
normal = { family = "CaskaydiaCove Nerd Font" }

[env]
term = "xterm-256color"
[colors.primary]
foreground = "#7F8CAA"

[scrolling]
history = 10000
